services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns
    container_name: cloudflare-ddns
    environment:
      - API_KEY=your_api_key_here
      - ZONE=example.com
      - SUBDOMAIN=vpn
    restart: unless-stopped
  wg-easy:
    image: weejewel/wg-easy
    container_name: wg-easy
    environment:
      # Change this to your host's public address
      - WG_HOST=www.example.com
      # Optional:
      - PASSWORD=P4ssw0rd
      - WG_PORT=51280
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      # - WG_DEFAULT_DNS=1.1.1.1
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
      # - WG_PRE_UP=echo "Pre Up" > /etc/wireguard/pre-up.txt
      # - WG_POST_UP=echo "Post Up" > /etc/wireguard/post-up.txt
      # - WG_PRE_DOWN=echo "Pre Down" > /etc/wireguard/pre-down.txt
      # - WG_POST_DOWN=echo "Post Down" > /etc/wireguard/post-down.txt
    volumes:
      - wireguard_data:/etc/wireguard
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
  tailscale:
    container_name: tailscale
    image: tailscale/tailscale:stable
    environment:
      - TS_SOCKET=/var/run/tailscale/tailscaled.sock
    hostname: outside-vpn
    volumes:
      - tailscale_data:/var/lib
      - /dev/net/tun:/dev/net/tun
    network_mode: host
    cap_add:
      - net_admin
      - sys_module
    command: tailscaled
    privileged: true
    restart: unless-stopped

volumes:
  wireguard_data:
    name: wireguard_data
  tailscale_data:
    name: tailscale_data
